// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFpD5y0sBsnaQozSPolDPZLmbdYXB8cBY',
    appId: '1:695591254821:web:63a9b24620ee631232b8cc',
    messagingSenderId: '695591254821',
    projectId: 'freshfarmilybackend',
    authDomain: 'freshfarmilybackend.firebaseapp.com',
    storageBucket: 'freshfarmilybackend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADgb2Xr7UKhDqLEHKWJin4_BUQelo7B5s',
    appId: '1:695591254821:android:91b7b9a97a882a5b32b8cc',
    messagingSenderId: '695591254821',
    projectId: 'freshfarmilybackend',
    storageBucket: 'freshfarmilybackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWz67fP0rx-dV_26lNyduEPtEGeWTpiU8',
    appId: '1:695591254821:ios:233fe5af78e8be8732b8cc',
    messagingSenderId: '695591254821',
    projectId: 'freshfarmilybackend',
    storageBucket: 'freshfarmilybackend.firebasestorage.app',
    iosBundleId: 'com.example.freshfarmily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWz67fP0rx-dV_26lNyduEPtEGeWTpiU8',
    appId: '1:695591254821:ios:233fe5af78e8be8732b8cc',
    messagingSenderId: '695591254821',
    projectId: 'freshfarmilybackend',
    storageBucket: 'freshfarmilybackend.firebasestorage.app',
    iosBundleId: 'com.example.freshfarmily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFpD5y0sBsnaQozSPolDPZLmbdYXB8cBY',
    appId: '1:695591254821:web:dbc266e15b9c817e32b8cc',
    messagingSenderId: '695591254821',
    projectId: 'freshfarmilybackend',
    authDomain: 'freshfarmilybackend.firebaseapp.com',
    storageBucket: 'freshfarmilybackend.firebasestorage.app',
  );
}
